version: "3.8"

services:
  db:
    image: mysql
    container_name: database_mysql
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_DATABASE=toughts_db
      - MYSQL_ROOT_PASSWORD=2512
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
